avoid-breaking-exported-api = true
cognitive-complexity-threshold = 25
enum-variant-name-threshold = 3
enum-variant-size-threshold = 200
literal-representation-threshold = 16384
matches-for-let-else = "Never"
max-fn-params-bools = 2
max-struct-bools = 100
max-trait-bounds = 3
single-char-binding-names-threshold = 5
too-large-for-stack = 200
too-many-arguments-threshold = 10
too-many-lines-threshold = 10000
trivial-copy-size-limit = 8
type-complexity-threshold = 250
unreadable-literal-lint-fractions = true
vec-box-size-threshold = 4096
verbose-bit-mask-threshold = 1
warn-on-all-wildcard-imports = false
