array_width = 60
binop_separator = "Back"
brace_style = "AlwaysNextLine"
chain_width = 70
combine_control_expr = false
comment_width = 100
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_params_layout = "Tall"
fn_call_width = 80
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 100
imports_granularity = "Crate"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
short_array_element_width_threshold = 10
single_line_if_else_max_width = 80
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
tab_spaces = 4
wrap_comments = true
